---
title: "RossThon18"
author: "JMBK"
date: "4/13/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Data Cleaning

```{r}
invisible(library(lubridate))
invisible(library(ggplot2))
invisible(library(dplyr))

stockData <- read.csv("stock_prices.csv")
eventData <- read.csv("events_US.csv")
airportData <- read.csv("airports.csv")
```

```{r}
fares <- read.csv("fares.csv")
fares$revenue_per_customer <- fares$revenue / fares$num_people
summary(fares$revenue)

flights <- read.csv("PRIMARY_flight_traffic.csv")
x <- flights %>% group_by(quarter, airline_id, origin_airport, destination_airport) %>% dplyr::count()

fares <- left_join(fares, x, by = c("quarter", "airline_id", "origin_airport", "destination_airport")) %>% rename(num_flights = n)

flights$X <- NULL
flights$wheels_off <- NULL
flights$wheels_on <- NULL

summary(fares)

fares <- filter(fares, num_people > 5)
fares <- filter(fares, airline_id == "AA"| airline_id == "AS"| airline_id == "B6"| airline_id == "DL"| airline_id == "EV"| airline_id == "F9"| airline_id == "HA"| airline_id == "NK"| airline_id == "OO"| airline_id == "UA"| airline_id == "VX"| airline_id == "WN")
fares <- filter(fares, num_flights > 12)
#assume one flight per week minimum for a commercial airline

fares$rev_customer_mile <- fares$revenue_per_customer/fares$distance

names(airportData)[names(airportData) == "airport_id"] <- "origin_airport"
fares <- merge(fares, airportData, by = "origin_airport")
fares$city <- NULL
fares$state <- NULL
fares$airport_name <- NULL
names(fares)[names(fares) == "latitude"] <- "origin_lat"
names(fares)[names(fares) == "longitude"] <- "origin_long"

names(airportData)[names(airportData) == "origin_airport"] <- "destination_airport"
fares <- merge(fares, airportData, by = "destination_airport")
fares$city <- NULL
fares$state <- NULL
fares$airport_name <- NULL
names(fares)[names(fares) == "latitude"] <- "destination_lat"
names(fares)[names(fares) == "longitude"] <- "destination_long"

```

```{r}
library(ggmap)
library(fiftystater)
map<-get_map(location='united states', zoom=4, source='google',color='color')
fares <- na.omit(fares)

fares1 <- filter(fares, origin_airport == "ATL")
ggmap(map) + geom_segment(
        aes(x=origin_long, y=origin_lat, xend = destination_long, yend = destination_lat, show_guide = TRUE, colour=rev_customer_mile), 
        data=fares1, alpha=.1, na.rm = T) + 
        scale_color_gradient(low="lightblue", high="red")


```
